appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: AjNN5/tqLmierpLWp1XFYWk/dE7fAxlIr/rpyOCy12pPlAFRaqpIyjoH6NFUCT9fa4vVM/WqIkl5/Zw8s5HwB8EJG5FHDOQ5nT9SaXc3/ET8stvf9I1e87SvIJGi9z3AXC3p8oKT0dVV9u1UAqRBPfqhP9zX+VcpF0ZgH97V6XFIYLNbyaBAFQCJf9gkotF1lTFilp8/3irrOnAlX5vaQRU6BTVuWHzHEED010s+fNmZVyCekzZOueDz6D4MXZj/SvxuZF4cdjIJDYIc9e5c8tFKIpBlvyMJT+JVWMaDrOA1+fNIf5Awvz3SBx+AtoGSgLt66BtNxPyQY0MRzJvFX9lfwOp8u6iEYs23ZOava7n2hgclrCE/2YHVcnQh/2MkJsGDfIkji5IC0vvBVVS/TH0KTWXYqUZ1XYHcr3TQJWmfnB3FAneane4fkgwQTJKcIDcLM/3fNmCRiqOc5MSTz1StAwVJzuCgFz/FVof3Ai1WU66/XXQXelAl/E/gDn9UI4Y3/q9LuwTDREgveHk+v2LKI38fMjpP4tPKL6xZsdJVlUSUZ71tTnmm67iX7cPYYQpO5aMw/Q3GEejHIC9RaipkEVe4gUeDF1U7f8rDeGk0UZ6X9Mqrd2VC0M/Mhtwm+ZJkM+tV2inACxYzA9LK11sEzezOVGocvXstXbuTo9o=}
